config/routes.rb
Rails.application.routes.draw do
  root to: "landing#index"

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'signin',
               sign_out: 'signout'
             },
             controllers: {
               registrations: 'registrations'
             }

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :churches, only: [:index]
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      get 'church', to: 'churches#index'
      get 'church/(:church_slug)', to: 'churches#show'
      get 'church/(:church_slug)/guides', to: 'guides#index'
      get 'church/(:church_slug)/guides/(:guide_slug)', to: 'guides#show'
    end
  end

  resources :admin, only: [:index]
  resources :users, except: [:show]

  post '/bible', to: 'bible#index'

  resources :graphics, only: %i[index create] do
    member do
      get '(:church_slug)', to: 'graphics#church_graphic'
    end
  end

  resources :churches

  get '/guides', to: redirect('/admin', status: 302)
  get '/guides/(:guide)/studies', to: redirect('/guides/%{guide}', status: 302)
  resources :guides, except: [:index] do
    resources :studies, except: [:index]
    member do
      post '/reorder', to: 'guides#reorder'
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :login_check
  helper_method :resource_name, :resource, :devise_mapping

  def index; end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

private

  def login_check
    redirect_to admin_index_path if user_signed_in?
  end

end

app/views/landing/index.html.erb
<div class="landing">
  <section class="landing__masthead">
    <div class="landing__innertube landing__masthead__lead">
      <%= image_tag('one21-inhand.png') %>
      <h1><strong>One21</strong> helps <span class="nobr">your church</span><br/>family disciple <span class="nobr">one another</span></h1>
    </div>
  </section>

  <section class="landing__cta">
    <div class="landing__innertube">
      <p>Reflect and discuss what you're hearing on Sundays in <span class="nobr">one-to-one groups</span></p>
      <a href="https://www.globe.church/resources/one21-launch" target="_blank" class="btn" rel="noopener">Read the introduction <span class="nobr">blog post</span></a>
    </div>  
  </section>

  <section class="landing__signin" id="signin">
    <div class="landing__innertube">
      <h2><strong>Sign in</strong> to your <span class="nobr">church account</span></h2>

      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <%= f.email_field :email, autocomplete: "email", placeholder: "Email Address", class: 'landing__signin__textfield' %>

        <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: 'landing__signin__textfield' %>

        <!--
        <% if devise_mapping.rememberable? -%>
          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        <% end -%>
        -->

        <%= f.submit "Sign in", class: "btn" %>
      <% end %>

      <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <p class="landing__signin__forgotten"><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
      <% end %>

      <p>One21 is a new service. Registration isn’t <span class="nobr">public (yet).</span></p>
      <p>You can subscribe to the (infrequent) newsletter to find out when it <span class="nobr">will be:</span> <a href="https://church.us14.list-manage.com/subscribe?u=3c53cfffa413d69cfa32538ca&id=6ebad6ef68" target="_blank" rel="noopener" class="nobr">Sign up</a></p>
    </div>
  </section>
</div>

<!--
<section id="introduction">

  <h2>One21 is a tool to help your church run one-to-ones</h2>

  <p>Introduction</p>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

</section>

<section id="churches">
  Four / five church logos who are using it…
</section>

<section id="feature-one">
  <h2>Reflect and discuss the sermon you heard on Sunday</h2>
</section>

<section id="feature-two">
  <h2>Draw from pre-written one-to-one studies</h2>
</section>

<section id="testimonials">
  <h2>What other people are saying</h2>
  <p>Steve said he liked it…</p>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>
</section>

<section id="feature-three">
  <h2>Built by a church for a church</h2>
  <p>This is scratching an itch we had…</p>
</section>

<footer>
  All the links
</footer>
-->