config/routes.rb
Rails.application.routes.draw do
  root to: "landing#index"

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'signin',
               sign_out: 'signout'
             },
             controllers: {
               registrations: 'registrations'
             }

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :churches, only: [:index]
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      get 'church', to: 'churches#index'
      get 'church/(:church_slug)', to: 'churches#show'
      get 'church/(:church_slug)/guides', to: 'guides#index'
      get 'church/(:church_slug)/guides/(:guide_slug)', to: 'guides#show'
    end
  end

  resources :admin, only: [:index]
  resources :users, except: [:show]

  post '/bible', to: 'bible#index'

  resources :graphics, only: %i[index create] do
    member do
      get '(:church_slug)', to: 'graphics#church_graphic'
    end
  end

  resources :churches

  get '/guides', to: redirect('/admin', status: 302)
  get '/guides/(:guide)/studies', to: redirect('/guides/%{guide}', status: 302)
  resources :guides, except: [:index] do
    resources :studies, except: [:index]
    member do
      post '/reorder', to: 'guides#reorder'
    end
  end

end

app/views/admin/index.html.erb
<div class="wrapper__section">
  <div class="wrapper__section__leadGraphic">
    <%= image_tag 'one21-background.jpg', alt: 'One21' %>
  </div>
  
  <% if @church %>
    <div class="wrapper__section__body">

      <section class="churchPrimer">

        <% if @church.graphic %>
          <div class="churchPrimer__img">
            <%= responsive_image_tag(@church.graphic.graphic_urls,
                                    sizes: ['(max-width: 460px) 100vw', '(max-width: 1080px) 50vw', '365px'],
                                    alt: @church.graphic.graphic_name) if @church.graphic.present? %>
          </div>
        <% end %>

        <h2 class="churchPrimer__title"><%= @church.church_name %></h2>
        <% if @church.city.present? %>
          <p><%= @church.city %></p>
        <% end %>
        
        <ul class="churchPrimer__details">
          <% if @church.url.present? %>
            <li><%= @church.url %></li>
          <% end %>

          <% if @church.email.present? %>
            <li><%= @church.email %></li>
          <% end %>

          <% if @church.phone.present? %>
            <li><%= @church.phone %></li>
          <% end %>

        </ul>

        <%= link_to('Update church details', edit_church_path(@church), class: "btn btn--textonly") %>
      </section>
    </div>
  <% end %>

</div>

<% if @current_user.churchadmin? || @current_user.superadmin? %>
<section class="wrapper__section churchPrimer">
  <h2 class="churchPrimer__title">Church users</h2>
  <ul class="churchPrimer__details">
  <% for u in @church.users %>
    <li class="<%= 'admin' if u.role == 'churchadmin' %>">
      <% if u.id == current_user.id %>
        <%= link_to("#{u.full_name}", edit_user_registration_path) %>
      <% else %>
        <%= link_to("#{u.full_name}", edit_user_path(u)) %>
      <% end %>
    </li>
  <% end %>
  </ul>

  <%= link_to('Add new user', new_user_path, class: "btn btn--textonly") %>
</section>
<% end %>

<% if @church %>
  <section class="wrapper__section guideOverview">

    <header class="wrapper__section__header">
      <div class="wrapper__section__header__content">
        <h2>Guides</h2>
      </div>

      <div class="wrapper__section__header__action">
        <%= link_to(t('guides.new'), new_guide_path, class: 'btn') %>
      </div>
    </header>

    <% if @guides.present? %>
      <div class="guideOverview__grid">
        <% for guide in @guides do %>
          <%= link_to(guide_path(guide), class: "guideOverview__grid__item guideTile") do %>
            <div class="guideTile__img">
              <img src="<%=guide.graphic.try(:graphic_thumbnail).try(:remote_url)%>" alt="">
              <% if guide.status == "draft" %>
                <span class="guideTile__img__chip chip"><%= guide.status %></span>
              <% end %>
            </div>

            <div class="guideTile_info">
              <h3><%= guide.guide_name %></h3>
              <p><%= guide.teaser %></p>
            </div>
            
            <div class="guideTile__action">
              <span class="btn btn--textonly">View</span>
            </div>
          <% end %>

        <% end %>
      </div>
    <% else %>
    <div class="emptyState emptyState--study">
      <p><%= t('guides.empty') %></p>
      <%= link_to(t('guides.new'), new_guide_path, class: 'btn btn--primary') %>
    </div>
    <% end %>
  </section>

<% end %>


<% if @church && !@church.verified %>
  <section class="toast toast--bottom">
    <h2 class="toast__heading"><%= t('gateway.unverified_msg.headline', church_name: @church.church_name) %></h2>
    <p><%= t('gateway.unverified_msg.description') %></p>
  </section>
<% end %>