config/routes.rb
Rails.application.routes.draw do
  root to: "landing#index"

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'signin',
               sign_out: 'signout'
             },
             controllers: {
               registrations: 'registrations'
             }

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :churches, only: [:index]
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      get 'church', to: 'churches#index'
      get 'church/(:church_slug)', to: 'churches#show'
      get 'church/(:church_slug)/guides', to: 'guides#index'
      get 'church/(:church_slug)/guides/(:guide_slug)', to: 'guides#show'
    end
  end

  resources :admin, only: [:index]
  resources :users, except: [:show]

  post '/bible', to: 'bible#index'

  resources :graphics, only: %i[index create] do
    member do
      get '(:church_slug)', to: 'graphics#church_graphic'
    end
  end

  resources :churches

  get '/guides', to: redirect('/admin', status: 302)
  get '/guides/(:guide)/studies', to: redirect('/guides/%{guide}', status: 302)
  resources :guides, except: [:index] do
    resources :studies, except: [:index]
    member do
      post '/reorder', to: 'guides#reorder'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  default_scope { order(family_name: :asc) }

  enum role: %i[user churchuser churchadmin superadmin]
  after_initialize :set_default_role, if: :new_record?

  belongs_to :church,
             optional: true,
             foreign_key: :churches_id,
             inverse_of: :users

  validates :email, :first_name, :family_name, presence: true

  def full_name
    "#{first_name} #{family_name}"
  end

  def set_default_role
    self.role ||= :churchadmin
  end

  def self.current=(user)
    Thread.current[:current_user] = user
  end

  def self.current
    Thread.current[:current_user]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :check_church_admin
  before_action :set_church

  def index
    check_super_admin
    @churches = churches
  end

  def new
    @user = User.new
  end

  def create
    u = User.find_by(email: user_params['email'])
    if !u
      u = User.new(user_params)

      if !current_user.superadmin? || !u.churches_id
        u.churches_id = @church.id
      end
    
      if u.invite!
        redirect_to admin_index_path, notice: "#{u.full_name} created" and return
      else
        redirect_to admin_index_path, alert: 'Failed saving!' and return
      end
    else
      redirect_to edit_user_path(u), alert: 'User already exists' and return
    end
  end

  def edit
    @user = user

    if !@user
      redirect_to admin_index_path, alert: 'No such user.' and return
    end

    if @user.churches_id != @church.id && current_user.role != 'superadmin'
      redirect_to admin_index_path, alert: 'That is not the user you were looking for.' and return
    end
    
    if @user == current_user
      redirect_to edit_user_registration_path
    end
  end

  def update
    user.attributes = user_params
    if user.save
      redirect_to users_path, notice: "#{user.first_name} updated" and return
    end
  end

  def destroy
    @user = user
    if @user.delete
      redirect_to admin_index_path, notice: "#{@user.first_name} removed" and return
    end
  end

private

  def set_church
    @church = current_user.church
  end

  def church_users
    @church_users ||= @church.users
    #@church_users ||= User.all
  end

  def churches
    @churches ||= Church.all
  end

  def users
    @users ||= User.all
  end

  def user
    @user ||= users.find_by(id: params[:id])
  end

  def check_church_admin
    if (!['churchadmin', 'superadmin'].include? current_user.role)
      redirect_to admin_index_path, alert: "You are not authorized to be go there"
    end
  end

  def check_super_admin
    if (!['superadmin'].include? current_user.role)
      redirect_to admin_index_path
    end
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :family_name,
                                 :email,
                                 :role,
                                 :churches_id)
  end

end

app/views/users/_form.html.erb
<%= form_for(@user,  html: { class: 'wrapper__section' }) do |f| %>

  <header class="wrapper__section__header">
    <div class="wrapper__section__header__content">
      <% if @user.id %>
        <h2>Edit User</h2>
      <% else %>
        <h2>Create User</h2>
      <% end %>
    </div>
  </header>

  <div class="wrapper__body">

    <%= render('shared/form_errors', m: @user) %>

    <div class="form__field">
      <%= f.text_field :first_name, class: 'form__input' %>
      <%= f.label :first_name, class: 'form__label' %>
    </div>

    <div class="form__field">
      <%= f.text_field :family_name, class: 'form__input' %>
      <%= f.label :family_name, class: 'form__label' %>
    </div>

    <div class="form__field">
      <%= f.text_field :email, class: 'form__input' %>
      <%= f.label :email, class: 'form__label' %>
    </div>

    <% if current_user.superadmin? %>
    <div class="form__field">
      <div class="form__input form__input--select">
        <%= f.collection_select :churches_id, Church.all, :id, :church_name %>
      </div>
      <%= f.label :church, class: 'form__label' %>
    </div>
    <% end %>

    <% if @user.id %>

      <div class="form__field">
        <ul class="form__input form__input--radio">
          <li>
            <%= f.radio_button(:role, "churchuser") %>
            <%= label(:role, "User", for: 'user_role_churchuser') %>
          </li>
          <li>
            <%= f.radio_button(:role, "churchadmin") %>
            <%= label(:role, "Admin", for: 'user_role_churchadmin') %>
          </li>
        </ul>

        <%= f.label :role, class: 'form__label' %>
      </div>

      <%= f.submit t('general.update'), class: 'btn btn--primary' %>
    <% else %>
    <%= f.hidden_field :role, value: 'churchuser' %>
      <%= f.submit t('general.create'), class: 'btn btn--primary' %>
    <% end %>

  </div>

<% end %>

<% if @user.id %>
<div class="wrapper__section">
  <hr />
  <p>Warning: this action cannot be undone:</p>
  <%= button_to t('general.delete', name: @user.full_name), @user, method: :delete, class: 'btn btn--danger btn--mini' %>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<section class="wrapper__section">
  <% for c in @churches%>
    <h1>
      <%= c.church_name %>
      <% if !c.verified? %> (Unverified)<% end %>
    </h1>
    <ul>
      <% for u in c.users %>
        <li class="<%= 'admin' if u.role == 'churchadmin' %>">
          <%= u.first_name%> <%= u.family_name%> (<%= u.email%>)
          <% if u.id == current_user.id %>
            <%= link_to('My Account', edit_user_registration_path) %>
          <% else %>
            <%= link_to('Update user', edit_user_path(u)) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= link_to('New church', new_church_path) %>
  <%= link_to('New user', new_user_path) %>

</section>

app/views/users/new.html.erb
<%= render 'form' %>