config/routes.rb
Rails.application.routes.draw do
  root to: "landing#index"

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'signin',
               sign_out: 'signout'
             },
             controllers: {
               registrations: 'registrations'
             }

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :churches, only: [:index]
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      get 'church', to: 'churches#index'
      get 'church/(:church_slug)', to: 'churches#show'
      get 'church/(:church_slug)/guides', to: 'guides#index'
      get 'church/(:church_slug)/guides/(:guide_slug)', to: 'guides#show'
    end
  end

  resources :admin, only: [:index]
  resources :users, except: [:show]

  post '/bible', to: 'bible#index'

  resources :graphics, only: %i[index create] do
    member do
      get '(:church_slug)', to: 'graphics#church_graphic'
    end
  end

  resources :churches

  get '/guides', to: redirect('/admin', status: 302)
  get '/guides/(:guide)/studies', to: redirect('/guides/%{guide}', status: 302)
  resources :guides, except: [:index] do
    resources :studies, except: [:index]
    member do
      post '/reorder', to: 'guides#reorder'
    end
  end

end

app/models/guide.rb
class Guide < ApplicationRecord

  has_many :studies,
           foreign_key: "guides_id",
           inverse_of: :guide,
           dependent: :destroy
  has_many :church_guides,
           dependent: :nullify
  has_many :churches,
           through: :church_guides

  belongs_to :graphic,
             foreign_key: :graphics_id,
             optional: true,
             inverse_of: :guides

  validates :guide_name, :slug, presence: true

  acts_as_url :guide_name,
              sync_url: true,
              force_downcase: true,
              url_attribute: :slug,
              only_when_blank: true,
              allow_duplicates: true

  enum status:  %i[draft published archived deleted]
  enum sorting: %i[date_desc date_asc ordered]
  after_initialize :set_default_status, if: :new_record?

  accepts_nested_attributes_for :church_guides

  scope :not_deleted, -> { where.not(status: 'deleted') }

  def to_param
    slug
  end

  def self.find_by_slug(guide_slug)
    find_by slug: guide_slug
  end

private

  def set_default_status
    self.status ||= :draft
  end

end

app/controllers/api/v1/guides_controller.rb
class Api::V1::GuidesController < ApiController

  def index
    # TODO: At some point add pagination into this mix:
    # https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-three

    guides
    if @guides.length.positive?
      json_response(@guides)
    else
      raise ActionController::RoutingError, 'Not Found'
    end
  end

  def show
    guide
    if @guide
      json_response(@guide,
                    :ok,
                    FullGuideSerializer)
    else
      raise ActionController::RoutingError, 'Not Found'
    end
  end

private

  def guides
    @guides ||= Guide.
                published.
                includes(:churches).
                where(churches: {slug: params[:church_slug],
                                 verified: true})
  end

  def guide
    g = guides.find_by!(slug: params[:guide_slug])
    return unless g
    sort_statement = case g.sorting
                     when 'date_desc'
                       'studies.published_at DESC NULLS FIRST'
                     when 'date_asc'
                       'studies.published_at ASC NULLS FIRST'
                     else
                       'studies.sort_order ASC'
                     end

    @guide = Guide.published.
             includes(:churches, :studies).
             where(
               churches: {
                 slug: params[:church_slug],
                 verified: true
               },
               guides: {slug: params[:guide_slug]},
               studies: {status: 'published'}
             ).
             where(
               "studies.published_at <= ?", Time.now.utc
             ).
             order(sort_statement).
             first
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  before_action :authenticate_user!

  def show
    @guide = guide
    @studies = studies
  end

  def new
    @guide = Guide.unscoped.new
    @guide.church_guides.build(church_id: current_user.churches_id)
  end

  def create
    @guide = Guide.unscoped.new(guide_params)
    if @guide.save
      flash[:notice] = "Guide created"
      redirect_to @guide
    else
      render 'new'
    end
  end

  def edit
    @guide = guide
  end

  def update
    guide.attributes = guide_params
    if guide.save
      if request.headers['TriggeredBy']
        render json: {new_status: @guide.status}
      else
        flash[:notice] = 'Guide updated'
        redirect_to guide_path(guide)
      end
    end
  end

  def reorder
    if (@orders = params[:studyIds]) && @orders.present?
      @orders = JSON.parse(params[:studyIds])
      if @orders.is_a?(Array) && @orders.size.positive?
        data = {}
        @orders.each_with_index do |id, index|
          data[id] = {sort_order: index}
        end
        Study.unscoped.all.update(data.keys, data.values)
      end
    end

    render json: ['win']
  end

private

  def guides
    @guides ||= Guide.
                includes(:church_guides).
                where(church_guides: {church_id: current_user.church.id,
                                      owner: true})
  end

  def guide
    @guide ||= guides.find_by!(slug: params[:id])
  end

  def studies
    if @studies
      @studies
    else
      @studies = guide.studies.where(status: %i[draft published])
      if @guide.sorting == "date_desc"
        @studies.order('published_at DESC NULLS FIRST')
      elsif @guide.sorting == "date_asc"
        @studies.order('published_at ASC NULLS FIRST')
      else
        @studies.order(sort_order: :asc)
      end

    end
  end

  def guide_params
    params.require(:guide).permit(:guide_name,
                                  :teaser,
                                  :description,
                                  :copyright,
                                  :status,
                                  :graphics_id,
                                  :sorting,
                                  :highlight_first,
                                  church_guides_attributes: [:church_id, :owner])
  end

end

app/views/guides/_form.html.erb
<%= form_for(@guide, html: { class: "form wrapper__section" }) do |f| %>

  <header class="wrapper__section__header">
    <div class="wrapper__section__header__content">
      <h2>Edit Guide</h2>
    </div>
  </header>

  <div class="wrapper__body">
    <%= render('shared/form_errors', m: @guide) %>

    <%= f.fields_for :church_guides do |cg| %>
      <%= cg.hidden_field :church_id, value: current_user.churches_id %>
      <%= cg.hidden_field :owner, value: true %>
    <% end %>

    <div class="form__field">
      <%= f.text_field :guide_name, class: 'form__input' %>
      <%= f.label :guide_name, class: 'form__label' %>
    </div>

    <div class="form__field">
      <%= f.text_area :teaser, class: 'form__input js-expandableTextArea' %>
      <%= f.label :teaser, class: 'form__label' %>
    </div>

    <div class="form__field">
      <%= f.text_area :description, class: 'form__input js-expandableTextArea' %>
      <%= f.label :description, class: 'form__label' %>
    </div>

    <div class="form__field">
      <%= f.text_field :copyright, class: 'form__input' %>
      <%= f.label :copyright, class: 'form__label' %>
    </div>

    <%= f.hidden_field :graphics_id %>
    <div
      class="js-imageUploader"
      data-inputId="guide_graphics_id"
      data-fieldLabel="Lead image"
      data-churchGraphicEndpoint="/graphics/<%= @current_user.church.slug %>"
      data-previewURL="<%= @guide.graphic.try(:graphic_960).try('remote_url') %>">
    </div>

    <div class="form__field">
      <span class="form__input form__input--inlineRadio">
        <%= f.collection_radio_buttons(:sorting,
                                      Guide.sortings.keys.map { |w| [w.humanize, w] },
                                      :second,
                                      :first) do |b|
                                        b.label { b.radio_button + b.label }
                                      end
        %>
      </span>
      <%= f.label :sorting, class: 'form__label' %>
    </div>

    <% if @guide.slug != 'sermons' %>
      <div class="form__field">
        <span class="form__input form__input--inlineRadio">
          <label>
          <%= f.check_box(:highlight_first) %>
            Promote on the homepage
          </label>
        </span>
        <%= f.label :highlight_first, class: 'form__label' %>
      </div>
    <% end %>

    <%= f.submit 'Save', class: 'form__submit btn btn--primary' %>
    
  </div>
<% end %>

app/views/guides/show.html.erb
<section class="wrapper__section">
  <% if @guide.graphic %>
    <div class="wrapper__section__leadGraphic">
      <%= responsive_image_tag(@guide.graphic.graphic_urls,
                               sizes: ['(max-width: 780px) 100vw', '780px'],
                               alt: @guide.guide_name) %>
    </div>
  <% end %>

  <header class="wrapper__section__header">
    <div class="wrapper__section__header__content">
      <h2><%= @guide.guide_name %></h2>
    </div>

    <div class="wrapper__section__header__action">
      <div
        class="js-stateSwitcher"
        data-model="guide"
        data-post-url="<%=guide_path(@guide) %>"
        data-current-state="<%= @guide.status %>">
        <%= @guide.status.humanize %>
      </div>
    </div>
  </header>


  <p><%= @guide.teaser %>

  <p>This is a guide produced by <%= @guide.churches.first.church_name %></p>

  <%= link_to(t('guides.edit', guide_name: @guide.guide_name), edit_guide_path(@guide), class: 'btn') %>

</section>

<section class="wrapper__section">
  <header class="wrapper__section__header">
    <div class="wrapper__section__header__content">
      <h2>Studies</h2>
    </div>

    <div class="wrapper__section__header__action">
      <%= link_to(t('studies.new'), new_guide_study_path(@guide), class: 'btn')%>
    </div>
  </header>

  <% if @studies.present? %>
  <ul class="sortableList js-sortable" data-push="<%= guide_path(@guide) %>/reorder">
    <% for study in @studies do %>
      <li class="sortable js-reorderable__item<% if @guide.sorting == 'ordered' %> sortable--active<% end %>" data-id="<%=study.id%>">
        
        <% if @guide.sorting == 'ordered' %>
          <div class="sortable__handle">|||</div> 
        <% end %>

        <div class="sortable__img">
          <%= responsive_thumbnail_tag(
            study.lead_image_thumbnails,
            sizes: ['75px'],
            alt: ""
          ) if study.lead_image_thumbnails %>
        </div>

        <div class="sortable__desc">
          <%= link_to(edit_guide_study_path(@guide, study)) do %>
            <h3><%= study.study_name %></h3>
            <% if study.passage_ref_json.present? %>
              <p><%= study.passage_str %></p>
            <% end %>

            <% if @guide.sorting != 'ordered' && study.published_at %>
              <p><%= study.state.humanize %>: <%= l study.published_at %></p>
            <% end %>

          <% end %>
        </div>

        <div
          class="sortable__actions js-stateSwitcher"
          data-model="study"
          data-schedulable="true"
          data-current-state="<%= study.state %>"
          data-post-url="<%=guide_study_path(@guide, study) %>">
          <%= study.state.humanize %>
        </div>
      </li>
    <% end %>
  </ul>
  <% else %>
  <div class="emptyState emptyState--study">
    <p><%= t('studies.empty') %></p>
    <%= link_to(t('studies.new'), new_guide_study_path(@guide), class: 'btn btn--primary')%>
  </div>
  <% end %>
</section>